### ISSUE TITLE
Buscar documentaciones: TypeScript, Solid, React...

### ISSUE THREAD

**Issue by UO271447** [Arquisoft/dede_es3a#13]
Aquí dejo un pequeño vídeo de introducción a TypeScript con los "Basics" . 
https://www.youtube.com/watch?v=ahCwqrYpIuM&ab_channel=Fireship

**Comment by uo68216** [comment]
Dejo aquí los enlaces que nos envió el profesor para tenerlo todo junto.

- [Curso de react](https://www.youtube.com/watch?v=T_j60n1zgu0&list=PLV8x_i1fqBw0B008sQn79YxCjkHJU84pC)
- [Playlist react + typescript](https://www.youtube.com/watch?v=T_j60n1zgu0&list=PLV8x_i1fqBw0B008sQn79YxCjkHJU84pC)
- [Curso de frontend + backend con testing](https://fullstackopen.com/es/)

**Comment by nixhyun** [comment]
He visto este vídeo sobre SOLID, que puede ser interesante
https://www.youtube.com/watch?v=2X50sKeBAcQ&list=PLVrGYEuzA86HS8yDTzKHXiqeTXxcON77n&index=1&ab_channel=BettaTech

**Comment by UO271411** [comment]
Vídeo explicativo (inglés) enfocado en el mismo ámbito de nuestro proyecto, una tienda online.
- [Parte de la implementación de una tienda online básica (explicado)](https://www.youtube.com/watch?v=AmIdY1Eb8tY&ab_channel=CodingwithBasir)
