### ISSUE TITLE
Problemas con Pod

### ISSUE THREAD

**Issue by UO271447** [Arquisoft/dede_es3a#150]
estoy encontrando problemas  en el manejo de pod para la creación de la vista login.

**Comment by UO277876** [comment]
Pagina: https://inrupt.net/

**Comment by UO277876** [comment]
npm install history@5 react-router-dom@6

**Comment by UO277876** [comment]
https://github.com/pglez82/solid-react-example

**Comment by UO277876** [comment]
https://docs.inrupt.com/developer-tools/javascript/react-sdk/application/
https://solid-ui-react-example.docs.inrupt.com/
https://github.com/inrupt/solid-ui-react-demo

**Comment by UO277876** [comment]
Falta el tema del provider

**Comment by UO277876** [comment]
Todo realizado
