### ISSUE TITLE
Dirección POD no funciona

### ISSUE THREAD

**Issue by UO271447** [Arquisoft/dede_es3a#180]
No somos el unico grupo al que VCARD le da problema, comentarlo por el foro de la asignatura.

**Comment by UO271447** [comment]
Investigar "getSolidDataSet" :D

**Comment by UO271411** [comment]
Puede ser de utilidad https://www.campusvirtual.uniovi.es/mod/forum/discuss.php?d=41871#p69619

**Comment by UO277876** [comment]
Estoy con la base, pero todavía no sé si funciona

**Comment by UO277876** [comment]
v1 hecha #202

**Comment by UO277876** [comment]
#208 Hecho
