### ISSUE TITLE
Incluir en el Readme los miembros del equipo

### ISSUE THREAD

**Issue by HugoLebredo** [Arquisoft/dede_es3a#2]
En el archivo Readme.md  del repositorio es debe crearse una sección llamada **Miembros del equipo**  en la que cada integrante realice un commit que incluya 2 cosas:

- Nombre completo
- UO

**Comment by uo68216** [comment]
Me añado en el readme

**Comment by nixhyun** [comment]
Me añado también al readme

**Comment by UO271447** [comment]
Me añado en el readme

**Comment by UO271411** [comment]
Todos los miembro han sido incluidos a falta del quinto integrante, que se encuentra de Erasmus y de momento no se unirá al proyecto.
