### ISSUE TITLE
Corregir punto 1

### ISSUE THREAD

**Issue by UO271411** [Arquisoft/dede_es3a#63]
Temas a modificar:
- [x] Descripción de la aplicacion
- [x] Cambiar los requisitos funcionales
- [x] Cambiar las Metas de Calidad
- [x] Poner un issue del diseño y corregirlo

**Comment by UO271447** [comment]
Metas de calidad cambiadas.

**Comment by UO271411** [comment]
Vista de requerimientos cambiada.

**Comment by UO271411** [comment]
Descripción de la aplicación modificada.
