### ISSUE TITLE
 Diseño preliminar de la interfaz de usuario.

### ISSUE THREAD

**Issue by uo68216** [Arquisoft/dede_es3a#68]
Se crearán esbozos en papel con el diseño de las principales pantallas de la aplicación para la siguiente reunión. Colaborarán todos los miembros del equipo.

**Comment by uo68216** [comment]
Sugiero la siguiente herramienta web para realizar los bocetos: [quickMockup](https://jdittrich.github.io/quickMockup/)

**Comment by UO277876** [comment]
Prototipos realizados

**Comment by UO271447** [comment]
Prototipos realizados

**Comment by UO271411** [comment]
Prototipos realizados
