### ISSUE TITLE
Requisitos funcionales duda

### ISSUE THREAD

**Issue by UO277876** [Arquisoft/dede_es3a#79]
No sé muy bien donde redactar los requisitos funcionales, me refiero, donde se quieren poner/redactar en el proyecto. Para los prototipos se usó una carpeta a parte en documentación, ¿pero aquí dónde se están poniendo? #67

**Comment by UO271411** [comment]
En el apartado 1 de la documentación se puso alguno, según se vaya avanzando el proyecto se puede mirar el hecho de trasladarlos a otro sitio para evitar condensar en exceso el primer punto de la documentación.
