### ISSUE TITLE
Fusionar develop con la rama main.

### ISSUE THREAD

**Issue by HugoLebredo** [Arquisoft/dede_es3a#8]
Fijaos en la imagen que incluyo de vuestro repositorio mas abajo

Os está diciendo que vuestra rama develop va 11 commits por delante de la rama master.
Mirad las diferencias, en la rama master el readme está en ingles mientras que en develop habeis cambiado todo el texto 👍

Si todo está correcto el siguiente paso es hacer avanzar la rama main al punto donde está develop. Podeis ver en la imagen inferior que el botón "Contribute" tiene el iconito de un pull request. Lo que teneis que hacer:
 - [x] Fusionar la rama develop con main dandole a ese botón.
 - [ ] En cuanto esté todo hecho es recomendable eliminar las ramas que habeis creado para subir los nombres, ahora existen 8 yno aportan nada para el futuro. Si os da miedo dejarlo para un poco más adelante cuando tengais más veteranía. Por cierto en "Insights/Network" Podeis ver un esquema de linea de tiempo con los commits y las ramas de vuestro proyecto. Suele ser util para tener una percepción general

![image](https://user-images.githubusercontent.com/58787059/152642250-3cd2e019-3d42-45eb-8533-dc5ad84e2559.png)

**Comment by uo68216** [comment]
Fusiono rama tras obtener revisión positiva del pull request
